### PR TITLE
Fix angle decodification error improved. Validation plot shows correct values

### PR DESCRIPTION
**Pull request by roberCO**
The plot generated for the test dataset shows many points in -1.5 and pi in the phi angle. 

original

It is wrong due a small error in the "decodification phase" (transform from predicted cos/sin to angles). @PabloAMC and me found the bug and we fixed it replacing the transformation with a different function of the numpy arctangent. The fixed plot:

fixed

Now, the predicted angles are correct and minifold seems to be more accurate than in the original plot.

### CODE REVIEW

**Comment by EricAlcaide** [comment]
Huge thanks. Gonna add you to the readme **collaborators** section.

**Comment by EricAlcaide** [comment]
Done

**Comment by EricAlcaide** [comment]
thanks for the contribution!

**Comment by EricAlcaide** [comment]
Could you create a pull request with: 
1. The notebook + the plot (not just the code changes)
2. The trained model in h5 format?

**Comment by roberCO** [comment]
Ok! I create a new PR

**Comment by roberCO** [comment]
Hi,

I just realize that I made a mistake when I commit my predicting angles
notebook version (there was an execution error and I didn't see it). Sorry
about that!!

I did a new pull request with the new version. Please check it if
everything is correct.

Really good job with Minifold!! I am a PhD student of Universidad
Complutense de Madrid. Other PhD student (Pablo Antonio Moreno) and me are
using your project for some experiments.

Cheers,
Roberto.

**Comment by EricAlcaide** [comment]
hey guys! contact me via email ( ericalcaide1@gmail.com ) please! i'd like to be in contact!

**Pull request merged**
