### PR TITLE
Added format conversion

### PR DESCRIPTION
**Pull request by PSN01**
The added script for format conversion is required to convert the predicted distances in RR format which can be utilized as input to a 3D structure modelling software known as GDFuzz3D.

### CODE REVIEW

**Comment by EricAlcaide** [comment]
Thanks! Will take a look asap

**Comment by EricAlcaide** [comment]
Could you explain why is the `modify_pssm.py` file needed? 

Also, could you write a couple instructions on how to exactly use the new RR conversion script? (it should go in the https://github.com/EricAlcaide/MiniFold#reproducing-the-results section, as the 6th step)

**Comment by SNPrabha** [comment]
Sir,

The modify pssm program is for extracting specific lines which are required
for model predictions. It is required for concatenating the amino acid
indices along with the protein sequence pssm so that it can be given
together as input to the model.predict() function. After that the predicted
results can be taken as input for RR format conversion.

**Comment by EricAlcaide** [comment]
Okay cool. Nice image in the `models/distance_pipeline/Tutorials/README.pdf` by the way. Please consider the contribution to the readme.md.

**Comment by PSN01** [comment]
Hi ,

The detailed description on how to use the RR_format code is given in the
README.pdf document which is in the models/distance_pipeline/Tutorials
folder.

**Pull request merged**
